name: "Setup HarmonyOS SDK"
description: "Set up a specific version of the HarmonyOS SDK and add the command-line tools to the PATH"
author: "HarmonyOS Dev"

# Define your inputs here.
inputs:
  version:
    description: 'The version of the sdk to setup'
    required: false
    default: 2.0.0.2

# Define your outputs here.
outputs:
  sdk-path:
    description: 'The path of installed sdk'

runs:
  using: node20
  main: dist/index.js
